name: main

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      filename: ${{ steps.filename.outputs.filename }}
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run build

      - name: filename
        id: filename
        run: echo "filename=app-$(date +'%Y.%m.%d')-${GITHUB_SHA::6}_linux_amd64.tgz" >> "$GITHUB_OUTPUT"

      - name: package
        run: tar cvzf ./${{ steps.filename.outputs.filename }} app

      - uses: actions/upload-artifact@v4
        with:
          name: "artifact"
          path: ./${{ steps.filename.outputs.filename }}
          if-no-files-found: error
          retention-days: 1

  upload:
    uses: taiidani/deploy-action/.github/workflows/publish-binary.yml@main
    needs: build
    with:
      filename: "${{ needs.build.outputs.filename }}"

  deploy:
    uses: taiidani/deploy-action/.github/workflows/nomad.yml@main
    needs: upload
    with:
      artifact: "${{ needs.upload.outputs.artifact }}"
      jobspec: middara.nomad
      url: https://middara.taiidani.com
